
services:
  php:
    build:
      context: ./php
    container_name: symfony-php
    volumes:
      - ./symfony:/var/www/html
    networks:
      - symfony-network

  nginx:
    image: nginx:latest
    container_name: symfony-nginx
    ports:
      - "8081:80" # Changed port to 8081
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www/html
    depends_on:
      - php
    networks:
      - symfony-network

  db:
    image: postgres:latest
    container_name: symfony-db
    environment:
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_pass
      POSTGRES_DB: symfony_db
    ports:
      - "5433:5432" # Changed port to 5433
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge
